### ISSUE TITLE
H2 scrolling bug and suggested fix

### ISSUE THREAD

**Issue by mickschonhut** [alphagov/tech-docs-template#185] opened 2019-04-04 14:49 UTC
Anytime the user scrolls past a header deeper than a H2, the highlighting on the left hand Nav jumps to the parent heading.

This wasn't fixed by Release 1.8.0.

Below is a diff against the alphagov/govuk_tech_docs of a simple fix we developed for this, if you'd like to adopt it.

diff --git a/lib/assets/javascripts/_modules/in-page-navigation.js b/lib/assets/javascripts/_modules/in-page-navigation.js
index e945023..951a058 100644
--- a/lib/assets/javascripts/_modules/in-page-navigation.js
+++ b/lib/assets/javascripts/_modules/in-page-navigation.js
@@ -121,7 +121,7 @@
 
 var $this = $(this);
 
- if (Math.floor($this.position().top) <= 0) {
+ if (Math.floor($this.position().top) <= 0 && $tocItems.filter('a[href$="#' + $this.attr('id') + '"]').length > 0) {
     result = $this;
   }
 });

**Comment by nickcolley** [comment] 2019-11-01 13:56
Thanks for raising, this is a duplicate of https://github.com/alphagov/tech-docs-gem/issues/142 so I'll close this out and you can follow along in that issue. :)

**Closed by nickcolley** 2019-11-01 13:56 UTC
