### ISSUE TITLE
Tables don't render properly when followed directly by heading with no characters between

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#139] opened 2017-12-04 11:05 UTC
Tables do not render properly when they are followed directly by a heading with no characters in between them. The table must have at least one character on a new line between it and the heading that follows in order for the table to work. With this error, the heading breaks as well.

**Comment by pgchamberlin** [comment] 2017-12-13 15:51
Is this a duplicate of #138 or something different?

**Comment by soupdragon99** [comment] 2017-12-13 16:46
It looks like this has been resolved:

"workaround tested successfully, we could update this in the doc or start to build a KB on our wiki for example." @jonathanglassman

**Closed** 2017-12-15 15:40 UTC
Labels: bug
