### ISSUE TITLE
Initial fragment not stored in the browser history

### ISSUE THREAD

**Issue by MatMoore** [alphagov/tech-docs-template#109] opened 2017-08-22 12:36 UTC
I clicked this link: https://govukpay-docs.cloudapps.digital/#contribute
Then I scrolled up and down, and the fragment in the URL changed.

I was expecting the back button to take me back to where I entered the docs, but the browser showed no page history.

I'm using Chrome Version 59.0.3071.115 (Official Build) (64-bit)

It seems like there is some code to handle this, but I didn't see anything obviously wrong with it https://github.com/alphagov/tech-docs-template/blob/master/template/source/javascripts/_modules/in-page-navigation.js#L43

**Comment by 36degrees** [comment] 2017-08-22 16:17
Thanks for reporting 🙂 

Our team is no longer working on this, but it might be useful to give some background:

We use `replaceState` rather than `pushState` when scrolling because otherwise scrolling through the document would add a huge number of history entries for every heading you scroll past.

If you click something in the navigation then that does push state, and clicking back would go back to where you were before you clicked the link.

I can see arguments either way but I think this is really 'working as designed'.

**Comment by nickcolley** [comment] 2019-11-01 13:10
Based on what Ollie has said here it seems like we can close this, but if you have suggestions on how to change this please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).

**Closed by nickcolley** 2019-11-01 13:10 UTC

**Comment by MatMoore** [comment] 2019-11-01 13:44
No problem. I'm not a huge fan of this functionality (every time I share a link I manually delete the fragment) but agree it is working as designed.

**Comment by nickcolley** [comment] 2019-11-01 13:45
@MatMoore I hope some of your frustrations will be resolved by fixing this: https://github.com/alphagov/tech-docs-gem/issues/145

**Comment by MatMoore** [comment] 2019-11-01 13:52
Yes they will! I was just going to ask about that 😁
